export const services = [
  {
    id: "swedish",
    title: "Swedish Massage",
    tagline: "The Art of Relaxation",
    description:
      "A gentle, flowing massage that soothes muscles, calms the nervous system, and restores your natural rhythm. Perfect for first-time visitors.",
    duration: "60 / 90 min",
    price: "From $120",
    icon: "🌿",
    category: "massage",
    benefits: ["Stress relief", "Improved circulation", "Deep relaxation", "Muscle ease"],
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
  },
  {
    id: "deep-tissue",
    title: "Deep Tissue",
    tagline: "Release & Restore",
    description:
      "Targeted pressure techniques that penetrate deep muscle layers, releasing chronic tension and restoring movement freedom.",
    duration: "60 / 90 min",
    price: "From $140",
    icon: "💆",
    category: "massage",
    benefits: ["Chronic pain relief", "Posture improvement", "Scar tissue healing", "Athletic recovery"],
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80",
  },
  {
    id: "hot-stone",
    title: "Hot Stone",
    tagline: "Warmth from Within",
    description:
      "Smooth basalt stones heated to the perfect temperature melt away tension as they glide across your body, creating profound warmth.",
    duration: "90 min",
    price: "From $165",
    icon: "🪨",
    category: "massage",
    benefits: ["Deep muscle warmth", "Energy alignment", "Improved sleep", "Stress reduction"],
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&q=80",
  },
  {
    id: "aromatherapy",
    title: "Aromatherapy",
    tagline: "Heal Through Scent",
    description:
      "Essential oils crafted from Australian botanicals are blended personally for you, creating an olfactory journey that heals body and mind.",
    duration: "60 / 90 min",
    price: "From $135",
    icon: "🌸",
    category: "wellness",
    benefits: ["Anxiety relief", "Mood uplift", "Sensory healing", "Immune support"],
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80",
  },
  {
    id: "prenatal",
    title: "Prenatal Care",
    tagline: "Gentle Support",
    description:
      "Specially designed for expecting mothers, this nurturing massage addresses the unique needs and discomforts of pregnancy with utmost care.",
    duration: "60 min",
    price: "From $130",
    icon: "🤱",
    category: "specialist",
    benefits: ["Reduced swelling", "Back pain relief", "Emotional support", "Better sleep"],
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80",
  },
  {
    id: "facial",
    title: "Healing Facial",
    tagline: "Skin Serenity",
    description:
      "A restorative facial using organic botanical ingredients. Cleanse, revive, and illuminate your skin with nature's finest remedies.",
    duration: "60 / 75 min",
    price: "From $115",
    icon: "✨",
    category: "wellness",
    benefits: ["Skin rejuvenation", "Deep cleansing", "Anti-aging", "Radiant glow"],
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
  },
  {
    id: "couples",
    title: "Couples Retreat",
    tagline: "Together in Calm",
    description:
      "Share the healing experience with someone special. Side-by-side treatments in our private suite, customised to both your needs.",
    duration: "90 min",
    price: "From $280",
    icon: "💑",
    category: "specialist",
    benefits: ["Shared relaxation", "Bonding experience", "Customised for two", "Private suite"],
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
  },
  {
    id: "reflexology",
    title: "Reflexology",
    tagline: "Heal from Your Feet",
    description:
      "Ancient pressure-point techniques applied to the feet to stimulate healing throughout the entire body. A transformative 45-minute experience.",
    duration: "45 / 60 min",
    price: "From $95",
    icon: "🦶",
    category: "wellness",
    benefits: ["Organ stimulation", "Stress relief", "Energy balance", "Circulation boost"],
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
  },
];

export const therapists = [
  {
    id: "maya",
    name: "Maya Thornton",
    title: "Lead Therapist",
    specialties: ["Swedish", "Hot Stone", "Aromatherapy"],
    experience: "8 years",
    bio: "Maya trained in Bali and brings a deeply intuitive approach to every session. Her gentle presence creates a safe space for true healing.",
    availability: ["Mon", "Tue", "Thu", "Fri", "Sat"],
    rating: 4.9,
    reviews: 128,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80",
  },
  {
    id: "james",
    name: "James Okafor",
    title: "Deep Tissue Specialist",
    specialties: ["Deep Tissue", "Sports Massage", "Reflexology"],
    experience: "6 years",
    bio: "A former sports physiotherapist, James combines clinical precision with therapeutic intuition for powerful results.",
    availability: ["Tue", "Wed", "Thu", "Sat", "Sun"],
    rating: 4.8,
    reviews: 95,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80",
  },
  {
    id: "lena",
    name: "Lena Nakashima",
    title: "Wellness Therapist",
    specialties: ["Prenatal", "Facial", "Swedish"],
    experience: "5 years",
    bio: "Lena's Japanese heritage infuses her practice with zen philosophy. She specialises in creating nurturing experiences for mothers-to-be.",
    availability: ["Mon", "Wed", "Fri", "Sat"],
    rating: 5.0,
    reviews: 72,
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&q=80",
  },
  {
    id: "sofia",
    name: "Sofia Marchetti",
    title: "Aromatherapy Expert",
    specialties: ["Aromatherapy", "Couples", "Facial"],
    experience: "7 years",
    bio: "Trained in Florence and Melbourne, Sofia crafts personalised essential oil blends that transform each session into a sensory journey.",
    availability: ["Mon", "Tue", "Wed", "Fri", "Sun"],
    rating: 4.9,
    reviews: 104,
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&q=80",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Sarah M.",
    location: "South Yarra",
    text: "I've tried many spas across Melbourne, but Serenity is truly in a different league. The moment you walk in, the world outside simply dissolves. Maya's hot stone massage was transcendent.",
    service: "Hot Stone Massage",
    rating: 5,
    avatar: "S",
    color: "#A8CBB7",
  },
  {
    id: 2,
    name: "David K.",
    location: "Fitzroy",
    text: "As someone who carries a lot of stress in my shoulders, James's deep tissue work has been life-changing. The studio itself feels like a sanctuary — I leave lighter every single time.",
    service: "Deep Tissue",
    rating: 5,
    avatar: "D",
    color: "#F6C1A6",
  },
  {
    id: 3,
    name: "Priya R.",
    location: "Carlton",
    text: "Lena made my prenatal massage an incredibly safe and loving experience. The whole team understood exactly what I needed. Can't imagine going anywhere else during this journey.",
    service: "Prenatal Care",
    rating: 5,
    avatar: "P",
    color: "#6D8B74",
  },
  {
    id: 4,
    name: "Tom & Ellie",
    location: "Richmond",
    text: "The couples retreat was the perfect anniversary gift. Sofia customised everything from the scents to the music. Pure magic. We've already booked for next month.",
    service: "Couples Retreat",
    rating: 5,
    avatar: "T",
    color: "#A8CBB7",
  },
  {
    id: 5,
    name: "Mei L.",
    location: "Toorak",
    text: "The booking experience alone sets Serenity apart — effortless and beautiful. The aromatherapy facial left my skin glowing for weeks. This place is a genuine treasure.",
    service: "Healing Facial",
    rating: 5,
    avatar: "M",
    color: "#F6C1A6",
  },
];

export const timeSlots = [
  "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM",
  "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM",
  "1:00 PM", "2:00 PM", "2:30 PM", "3:00 PM",
  "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM",
  "5:30 PM", "6:00 PM", "6:30 PM",
];

export const journeySteps = [
  {
    step: "01",
    title: "Arrive & Unwind",
    description: "A warm welcome with herbal tea and a moment to transition from your day to your healing space.",
    icon: "🍵",
  },
  {
    step: "02",
    title: "Personalise",
    description: "Your therapist takes time to understand your body, your stress, and your goals for the session.",
    icon: "🌿",
  },
  {
    step: "03",
    title: "Deep Healing",
    description: "Surrender to the experience. Every technique applied with intention, every moment crafted for you.",
    icon: "✨",
  },
  {
    step: "04",
    title: "Restore & Reflect",
    description: "Ease back gently with warm water, quiet space, and guidance on maintaining your wellbeing.",
    icon: "🌸",
  },
];

export const bookings = [
  {
    id: "b001",
    service: "Swedish Massage",
    therapist: "Maya Thornton",
    date: "Tuesday, 8 April 2026",
    time: "2:00 PM",
    duration: "90 min",
    status: "upcoming",
    price: "$155",
  },
  {
    id: "b002",
    service: "Aromatherapy",
    therapist: "Sofia Marchetti",
    date: "Saturday, 15 March 2026",
    time: "11:00 AM",
    duration: "60 min",
    status: "completed",
    price: "$135",
  },
  {
    id: "b003",
    service: "Hot Stone Massage",
    therapist: "Maya Thornton",
    date: "Friday, 28 February 2026",
    time: "4:00 PM",
    duration: "90 min",
    status: "completed",
    price: "$165",
  },
];
